### ISSUE TITLE
review 意见

### ISSUE THREAD

**Issue by killme2008** [leancloud/js-push-sdk#10]
- 命名上是否遵循 `AV`的 namespace 更合适?
- event模型很赞，很适合推送。
- `installationId` 其实我们已经在 js sdk 里的 localStorage 存储了一份，是否在存在 js sdk 的时候复用？参见
  https://github.com/leancloud/javascript-sdk/blob/master/lib/av.js#L1448-1473，用户使用我们这两个 sdk，无需生成和保存两份 installation。
- `pushObject.send` 方法已经有 `AV.Push` https://github.com/leancloud/javascript-sdk/blob/master/lib/av.js#L9237-9259
- 是否应该提供 api doc?

@wangxiao

**Comment by wangxiao** [comment]
#### 感谢晓丹的 review，么么嗒。。。
- **命名上是否遵循 AV 的 namespace 更合适?**
  - 考虑公司名字已经是 LeanCloud 了，名字是 lc 更加合适。
  - 然后考虑大写不如小写输入快捷，所以命名空间定为 lc。
  - Push 的 JavaScript SDK 没有什么包袱，不需要依赖 AV 什么，所以借着 2.0 干脆就直接改过来，不为以后留坑。
    <br><br>
- **event 模型很赞，很适合推送。**
  - 😳 难道这就是传说中的「英雄所见略同」么。。。
    <br><br>
- **installationId 其实我们已经在 js sdk 里的 localStorage 存储了一份，是否在存在 js sdk 的时候复用？**
  - 看了下生成方式，确实是应该复用的，我会去改下。
    <br><br>
- **pushObject.send 方法已经有 AV.Push**   
  - 这个 send 是该 SDK 的 send 方法，相当于把 Push 的功能聚合到这个统一的 Push SDK 中。
  - 而且，如果用户只需要推送功能，使用这个 Push SDK 的 send 更轻量些，依赖少。
    <br><br>
- **是否应该提供 api doc?**
  - 提供，考虑如果没问题，先发到我们的文档上，目前还是少部分用户试用中。
    <br>
    <br>

**Comment by killme2008** [comment]
命名上倾向于还是继续使用 AV，类似 iOS 哪怕改名了还是 NS 开头一样，保持一个一致的风格。

其他没有太多意见了。

**Comment by wangxiao** [comment]
麻烦 @killme2008 和 @sunng87 再看下。
https://github.com/leancloud/js-push-sdk/pull/14
