### ISSUE TITLE
如果客户端不传 installationId 服务器端自动生成？

### ISSUE THREAD

**Issue by wangxiao** [leancloud/js-push-sdk#20]
这个之前讨论过，目前 Web 是客户端生成的，是不是可以服务端生成下？（更能保证唯一之类的）
@sunng87

**Comment by sunng87** [comment]
installation 需要持久化，如果要生成的话，可能 API 那端生成比较好 @killme2008

**Comment by wangxiao** [comment]
就是类似的，实时通信、Push 服务都是，如果不传入 id，是不是服务端可以自动生成？总觉得客户端生成不是太靠谱，iOS 和 Android 主要是 Apple 和 Google 给生成好了，但是 web 没有。
