### ISSUE TITLE
subscribe方法已经不能使用

### ISSUE THREAD

**Issue by rapidhere** [leancloud/js-push-sdk#23]
正常工作需要在ajax时做以下修改:
-    url中需要加入设备objectId
-    方法改为put

**Comment by wangxiao** [comment]
您好，我这边运行现在这个版本 demo 中的 test.js 来测试，全部都是可以运行的。
如果你那边不能工作，是否有报错呢？

**Comment by rapidhere** [comment]
如果修改为两个test1.js和test2.js,在test1.js中订阅一个频道,再通过test2.js向这个频道推送,我的试验结果是收不到推送的.

同时,在启动demo后,leancloud的后端中也并没有看到相关的channel被订阅,但是,如果自己订阅了一个频道后朝这个频道推送是可以的,这个原因我不是很清楚.

我做出的修改是根据官方文档中关于更新installation中的RESTApi的说明:[连接](https://leancloud.cn/docs/rest_api.html#更新安装对象)

**Comment by wangxiao** [comment]
你在订阅和推送的时候，能看下「调试器」-「控制台」-「网络」中的网络请求情况么？
查看下，订阅一个频道是否报错？
你是不是配置过「JavaScript 安全域名」？

**Comment by rapidhere** [comment]
没有报错,我也没有配置过安全域名,但是情况和我之前说的一样

**Comment by wangxiao** [comment]
好的，我再试试看。

**Comment by wangxiao** [comment]
这是一个 bug，感谢反馈。

**Comment by wangxiao** [comment]
https://github.com/wangxiao/js-push-sdk/commit/a14667e48479b700dbb763368305f9f8bad6183e

**Comment by wangxiao** [comment]
已经发布 https://github.com/leancloud/js-push-sdk/releases/tag/2.0.2
