### ISSUE TITLE
没有正确处理 prod 和 deviceProfile ?

### ISSUE THREAD

**Issue by killme2008** [leancloud/js-push-sdk#39]
这里没有考虑传入 `prod: "dev"` 这种情况，设置使用测试证书或者 `deviceProfile` 设置自定义证书。

https://github.com/leancloud/js-push-sdk/blob/master/src/AV.push.js#L377-L381

**Comment by killme2008** [comment]
@wangxiao

**Comment by wangxiao** [comment]
https://github.com/leancloud/js-push-sdk/pull/42
