### ISSUE TITLE
Demo已经不能用了

### ISSUE THREAD

**Issue by nicecui** [leancloud/js-push-sdk#40]
下载下来，运行，出现图中的情况：
<img width="776" alt="2015-10-30 3 11 17" src="https://cloud.githubusercontent.com/assets/10130959/10840333/34babe5a-7f19-11e5-99e4-855f8171cc8e.png">

**Comment by wangxiao** [comment]
因为使用的 File:/// 访问的，所以被 Web 端安全域名设置给拒绝掉了。
