### ISSUE TITLE
push.send没办法给iOS测试环境发推送

### ISSUE THREAD

**Issue by nicecui** [leancloud/js-push-sdk#41]
push.send内的参数，即使定义了prod:"dev"，也会推送到iOS开发环境。

**Comment by killme2008** [comment]
重复了 https://github.com/leancloud/js-push-sdk/issues/39

**Comment by wangxiao** [comment]
好的，我修复下，忽略了。

**Comment by wangxiao** [comment]
https://github.com/leancloud/js-push-sdk/pull/42
