### ISSUE TITLE
AV.push.js 132行缺少变量的声明

### ISSUE THREAD

**Issue by wenzhihong2003** [leancloud/js-push-sdk#44]
``` js
id = tool.getId(); //132行
options.id = id;
engine.sendId(options, function(data) {
  tool.storage(itemName, id);
});
return id;
```

这里的 id缺少变量的声明吧, 要不然成为了一个全局变量了. 应改为 var id = tool.getId();

**Comment by wangxiao** [comment]
确实，非常感谢。
https://github.com/leancloud/js-push-sdk/pull/45/files

**Comment by wenzhihong2003** [comment]
:+1: 好快的速度. 这两天在狂看你们的文档. 谢谢, 做得真的不错. 减轻开发者不少工作量

**Comment by wenzhihong2003** [comment]
问一下, 这个id也是可以由我们的应用自动来生成的吧. 比如在应用里我们想给系统里的每个用户在建立的时候就生成一个, 而不是每次打开浏览器时生成一个. (当然看代码, 知道这个id生成好后会存在localstore里)

**Comment by wangxiao** [comment]
暂时不支持用户自定义生成，但是可以获取。
在 av.push 的实例中，通过 pushObject.installationId 可以获取得到。
